rvm: 2.1.3
language: objective-c

before_script:
  - brew update
  - brew outdated xctool || brew upgrade xctool

script:
  - xctool -project StridableNSDate.xcodeproj -scheme StridableNSDate -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -reporter pretty
  - xcodebuild -project StridableNSDate.xcodeproj -scheme StridableNSDate -destination 'platform=iOS Simulator,name=iPhone 6' test | xcpretty -c && exit ${PIPESTATUS[0]}